class_name StandingPositionOverrideStore
extends RefCounted

const JsonFileLoaderScript := preload("res://scripts/core/json_file_loader.gd")
const CharacterAssetKeysScript := preload("res://scripts/core/character_asset_keys.gd")

const NOTE := "Generated by StandingPositionCalibrator. Values are pixel offsets from the face-centered bust layout."

var user_path := ""
var default_path := ""


func _init(next_user_path: String = "", next_default_path: String = "") -> void:
	user_path = next_user_path
	default_path = next_default_path


func set_paths(next_user_path: String, next_default_path: String) -> void:
	user_path = next_user_path
	default_path = next_default_path


func load_offsets() -> Dictionary:
	for path in [user_path, default_path]:
		var loaded := JsonFileLoaderScript.read_dictionary(String(path), "standing position override JSON", false)
		if String(loaded.get(JsonFileLoaderScript.KEY_ERROR, "")) == JsonFileLoaderScript.ERROR_FILE_MISSING:
			continue
		return {
			CharacterAssetKeysScript.KEY_OFFSETS: _offsets_from_loaded(loaded),
			CharacterAssetKeysScript.KEY_LOADED_PATH: String(path)
		}
	return {
		CharacterAssetKeysScript.KEY_OFFSETS: {},
		CharacterAssetKeysScript.KEY_LOADED_PATH: ""
	}


func save_offsets(offsets: Dictionary) -> bool:
	var text := JSON.stringify(payload(offsets), "\t")
	var ok := write_text(user_path, text)
	write_text(default_path, text)
	return ok


static func payload(offsets: Dictionary) -> Dictionary:
	return {
		CharacterAssetKeysScript.KEY_VERSION: 1,
		CharacterAssetKeysScript.KEY_NOTE: NOTE,
		CharacterAssetKeysScript.KEY_OFFSETS: offsets.duplicate(true)
	}


static func read_offsets(path: String) -> Dictionary:
	var loaded := JsonFileLoaderScript.read_dictionary(path, "standing position override JSON", false)
	return _offsets_from_loaded(loaded)


static func write_text(path: String, text: String) -> bool:
	if path.is_empty():
		return false
	var file := FileAccess.open(path, FileAccess.WRITE)
	if file == null:
		push_warning("Could not write standing position overrides: %s" % path)
		return false
	file.store_string(text)
	file.close()
	return true


static func _offsets_from_loaded(loaded: Dictionary) -> Dictionary:
	if not bool(loaded.get(JsonFileLoaderScript.KEY_OK, false)):
		return {}
	return Dictionary(loaded.get(JsonFileLoaderScript.KEY_DATA, {})).get(CharacterAssetKeysScript.KEY_OFFSETS, {})
