extends "res://scripts/tests/test_scene_tree.gd"

const IntroTitleViewConfigScript := preload("res://scripts/ui/intro_title_view_config.gd")
const PanelLayoutHelpersScript := preload("res://scripts/ui/panel_layout_helpers.gd")


func _initialize() -> void:
	_expect(IntroTitleViewConfigScript.BACKGROUND_NAME == "Background", "background node name should stay stable")
	_expect(IntroTitleViewConfigScript.CONTENT_NAME == "Content", "content node name should stay stable")
	_expect(IntroTitleViewConfigScript.LAYOUT_NAME == "MobileTitleLayout", "layout node name should stay stable")
	_expect(IntroTitleViewConfigScript.TITLE_LOGO_NAME == "TitleLogo", "title logo node name should stay stable")
	_expect(IntroTitleViewConfigScript.START_BUTTON_FRAME_NAME == "StartButtonFrame", "start button frame node name should stay stable")
	_expect(IntroTitleViewConfigScript.START_BUTTON_HIT_AREA_NAME == "StartButtonHitArea", "start hit-area node name should stay stable")
	_expect(IntroTitleViewConfigScript.CONTINUE_BUTTON_FRAME_NAME == "ContinueButtonFrame", "continue button frame node name should stay stable")
	_expect(IntroTitleViewConfigScript.CONTINUE_BUTTON_IMAGE_NAME == "ContinueButtonImage", "continue button image node name should stay stable")
	_expect(IntroTitleViewConfigScript.CONTINUE_BUTTON_NAME == "ContinueButton", "continue button node name should stay stable")
	_expect(IntroTitleViewConfigScript.GALLERY_BUTTON_FRAME_NAME == "GalleryButtonFrame", "gallery button frame node name should stay stable")
	_expect(IntroTitleViewConfigScript.GALLERY_BUTTON_IMAGE_NAME == "GalleryButtonImage", "gallery button image node name should stay stable")
	_expect(IntroTitleViewConfigScript.GALLERY_BUTTON_NAME == "GalleryButton", "gallery button node name should stay stable")
	_expect(IntroTitleViewConfigScript.DEVELOPER_QUICK_BUTTON_NAME == "DeveloperQuickLaunchButton", "developer button node name should stay stable")
	_expect(IntroTitleViewConfigScript.KEY_TITLE_LOGO == "title_logo", "title logo ref key should stay stable")
	_expect(IntroTitleViewConfigScript.KEY_START_BUTTON_FRAME == "start_button_frame", "start frame ref key should stay stable")
	_expect(IntroTitleViewConfigScript.KEY_START_BUTTON == "start_button", "start button ref key should stay stable")
	_expect(IntroTitleViewConfigScript.KEY_CONTINUE_BUTTON == "continue_button", "continue button ref key should stay stable")
	_expect(IntroTitleViewConfigScript.KEY_GALLERY_BUTTON == "gallery_button", "gallery button ref key should stay stable")
	_expect(IntroTitleViewConfigScript.KEY_DEVELOPER_QUICK_BUTTON == "developer_quick_button", "developer button ref key should stay stable")
	_expect(IntroTitleViewConfigScript.OPTION_BACKGROUND_PATH == "background_path", "background option key should stay stable")
	_expect(IntroTitleViewConfigScript.OPTION_TITLE_LOGO_PATH == "title_logo_path", "title logo option key should stay stable")
	_expect(IntroTitleViewConfigScript.OPTION_START_BUTTON_PATH == "start_button_path", "start button option key should stay stable")
	_expect(IntroTitleViewConfigScript.OPTION_SHOW_CONTINUE_BUTTON == "show_continue_button", "continue option key should stay stable")
	_expect(IntroTitleViewConfigScript.OPTION_CONTINUE_BUTTON_PATH == "continue_button_path", "continue image option key should stay stable")
	_expect(IntroTitleViewConfigScript.OPTION_CONTINUE_TEXT == "continue_text", "continue text option key should stay stable")
	_expect(IntroTitleViewConfigScript.OPTION_SHOW_GALLERY_BUTTON == "show_gallery_button", "gallery option key should stay stable")
	_expect(IntroTitleViewConfigScript.OPTION_GALLERY_BUTTON_PATH == "gallery_button_path", "gallery image option key should stay stable")
	_expect(IntroTitleViewConfigScript.OPTION_GALLERY_TEXT == "gallery_text", "gallery text option key should stay stable")
	_expect(IntroTitleViewConfigScript.OPTION_SHOW_DEVELOPER_QUICK_LAUNCH == "show_developer_quick_launch", "developer quick-launch option key should stay stable")
	_expect(IntroTitleViewConfigScript.OPTION_DEVELOPER_QUICK_TEXT == "developer_quick_text", "developer quick text option key should stay stable")
	_expect(IntroTitleViewConfigScript.CALLBACK_START_PRESSED == "start_pressed", "start callback key should stay stable")
	_expect(IntroTitleViewConfigScript.CALLBACK_CONTINUE_PRESSED == "continue_pressed", "continue callback key should stay stable")
	_expect(IntroTitleViewConfigScript.CALLBACK_GALLERY_PRESSED == "gallery_pressed", "gallery callback key should stay stable")
	_expect(IntroTitleViewConfigScript.CALLBACK_DEVELOPER_QUICK_LAUNCH_PRESSED == "developer_quick_launch_pressed", "developer callback key should stay stable")
	_expect(int(IntroTitleViewConfigScript.CONTENT_MARGIN.get(PanelLayoutHelpersScript.KEY_TOP, 0)) == 54, "content top margin should preserve current layout")
	_expect(int(IntroTitleViewConfigScript.CONTENT_MARGIN.get(PanelLayoutHelpersScript.KEY_BOTTOM, 0)) == 28, "content bottom margin should lower the button stack")
	_expect(IntroTitleViewConfigScript.LAYOUT_SEPARATION == 10, "layout separation should keep the image buttons tightly grouped")
	_expect(IntroTitleViewConfigScript.TITLE_LOGO_SIZE == Vector2(620, 330), "title logo size should preserve current layout")
	_expect(IntroTitleViewConfigScript.START_BUTTON_FRAME_SIZE == Vector2(400, 72), "start frame size should use the small unified image button size")
	_expect(IntroTitleViewConfigScript.CONTINUE_BUTTON_SIZE == Vector2(400, 72), "continue button size should use the small unified image button size")
	_expect(IntroTitleViewConfigScript.GALLERY_BUTTON_SIZE == Vector2(400, 72), "gallery button size should use the small unified image button size")
	_expect(IntroTitleViewConfigScript.DEVELOPER_BUTTON_SIZE == Vector2(540, 56), "developer button size should preserve current layout")
	_expect(IntroTitleViewConfigScript.FOCUS_BORDER_WIDTH == 3, "focus border should preserve current layout")

	print("Intro title view config smoke test passed.")
	finish_test()


func _expect(condition: bool, message: String) -> void:
	if not condition:
		push_error(message)
		fail_test()
